---
version: "3.7"
services:
  ddclient:
    image: ghcr.io/torresmvl/ddclient
    command: -foreground -noquiet -verbose
    volumes:
      - ./config:/etc/ddclient:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
