---
version: '3.8'
services:
  ddclient:
    image: ghcr.io/torresmvl/ddclient:latest
    command: --foreground --syslog --verbose --file /run/secrets/ddclient.conf --cache /etc/ddclient/.cache/ddclient.cache
    networks:
      - private
    volumes:
      - cache:/etc/ddclient/.cache:rw
    secrets:
      - ddclient.conf
    healthcheck:
      test: ['CMD', 'curl', 'https://yourdomain.tld']
      timeout: 30s
      interval: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

secrets:
  ddclient.conf:
    file: ./config/ddclient.conf

networks:
  private:
    driver: overlay
    attachable: false
    driver_opts:
      encrypted: 'true'

volumes:
  cache:
