---
version: '3.8'
services:
  ddclient:
    build:
      context: .
    image: ghcr.io/torresmvl/ddclient:latest
    command: --foreground --debug --noquiet --verbose
    volumes:
      - ./config/ddclient.conf:/etc/ddclient/ddclient.conf:ro
    restart: unless-stopped
